# Image of the cluster-gateway instances
image: oamdev/cluster-gateway-addon-manager:v1.1.7.ocm.2

clusterGateway:
  image: oamdev/cluster-gateway:v1.1.7
  installNamespace: vela-system
  secretNamespace: open-cluster-management-credentials
# Number of replicas
replicas: 1

manualSecretManagement: true
konnectivityEgress: false