apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccount: cluster-gateway
      volumes:
        - name: proxy-client
          secret:
            secretName: proxy-client
        - name: proxy-server-ca
          secret:
            secretName: proxy-server-ca
      containers:
        - name: gateway
          image: {{ .Values.image }}
          args:
            - --secure-port=9443
            - --secret-namespace={{ .Values.secretNamespace }}
            {{ .ocmIntegration.enabled }}
            - --ocm-integration=true
            {{ .ocmIntegration.clusterProxy.enabled }}
            - --proxy-host={{ .ocmIntegration.clusterProxy.endpoint.host }}
            - --proxy-port={{ .ocmIntegration.clusterProxy.endpoint.port }}
            - --proxy-ca-cert=/etc/ca/ca..ocmIntegration.clusterProxy.crt
            - --proxy-cert=/etc/tls/tls.crt
            - --proxy-key=/etc/tls/tls.key
            {{ end }}
            {{ end }}
            # TODO: certificate rotation, otherwise the self-signed will expire in 1 year
          {{ .ocmIntegration.clusterProxy.enabled }}
          volumeMounts:
            - name: proxy-client
              mountPath: "/etc/tls/"
              readOnly: true
            - name: proxy-server-ca
              mountPath: "/etc/ca/"
              readOnly: true
            {{ end }}
          ports:
            - containerPort: 9443
